import { XlsxColumnNode } from "./xlsx-table";

export const kesintiColumns: XlsxColumnNode[] = [
  { label: "Kesinti Kodu (1)", key: "kesintiKodu", vertical: true },
  { label: "KADEME (2)", key: "kademe", vertical: true },
  {
    label: "Kesintinin Yeri (3)",
    children: [
      { label: "İL (3A)", key: "il", vertical: true },
      { label: "İLÇE (3B)", key: "ilce", vertical: true },
      { label: "Şebeke Unsuru Tipi (3C)", key: "sebekeTipi", vertical: true },
      { label: "Şebeke Unsuru Kodu (3D)", key: "sebekeKodu", vertical: true },
    ],
  },
  {
    label: "Kesintinin Kök Nedeni (4)",
    key: "kesintiKokNedeni",
    vertical: true,
  },
  {
    label: "Kesintinin Sınıfı (5)",
    children: [
      { label: "Kaynağa Göre (5A)", key: "sinif_kaynaga", vertical: true },
      { label: "Süreye Göre (5B)", key: "sinif_sureye", vertical: true },
      { label: "Sebebe Göre (5C)", key: "sinif_sebebe", vertical: true },
      { label: "Bildirime Göre (5D)", key: "sinif_bildirime", vertical: true },
    ],
  },
  {
    label: "Kesintinin Başlama Tarih ve Zamanı (6)",
    key: "baslama",
    vertical: true,
  },
  {
    label: "Kesintinin Sona Erme Tarih ve Zamanı (7)",
    key: "sonaErme",
    vertical: true,
  },
  {
    label: "Kesinti Süresi (Saat) (8)",
    key: "kesintiSuresiSaat",
    vertical: true,
  },
  {
    label: "Kesintiden Etkilenen Kullanıcılar (9)",
    children: [
      {
        label: "Mesken",
        vertical: true,

        children: [
          { label: "OG", key: "mesken_og" },
          { label: "AG", key: "mesken_ag" },
        ],
      },
      {
        label: "Tarımsal Sulama",
            vertical: true ,

        children: [
          { label: "OG", key: "tarimsal_og" },
          { label: "AG", key: "tarimsal_ag" },
        ],
      },
      {
        label: "Ticarethane",
            vertical: true ,

        children: [
          { label: "OG", key: "ticarethane_og" },
          { label: "AG", key: "ticarethane_ag" },
        ],
      },
      {
        label: "Sanayi",
            vertical: true ,

        children: [
          { label: "OG", key: "sanayi_og" },
          { label: "AG", key: "sanayi_ag" },
        ],
      },
    ],
  },
  {
    label: "Dağıtılmayan Enerji (kWh) (10)",
    children: [
      {
        label: "Mesken",
            vertical: true ,

        children: [
          { label: "OG", key: "enerji_mesken_og" },
          { label: "AG", key: "enerji_mesken_ag" },
        ],
      },
      {
        label: "Tarımsal Sulama",
            vertical: true ,

        children: [
          { label: "OG", key: "enerji_tarimsal_og" },
          { label: "AG", key: "enerji_tarimsal_ag" },
        ],
      },
      {
        label: "Ticarethane",
            vertical: true ,

        children: [
          { label: "OG", key: "enerji_ticarethane_og" },
          { label: "AG", key: "enerji_ticarethane_ag" },
        ],
      },
      {
        label: "Sanayi",
            vertical: true ,

        children: [
          { label: "OG", key: "enerji_sanayi_og" },
          { label: "AG", key: "enerji_sanayi_ag" },
        ],
      },
    ],
  },
  {
    label: "Toplam Dağıtılmayan Enerji (kWh) (11)",
    key: "total_not_delivered_kwh",
    vertical: true,
  },
];

export const kesintiDataXlsx = [
  {
    kesintiKodu: "97082",
    kademe: "DM",
    il: "MARDİN",
    ilce: "DARGEÇİT",
    sebekeTipi: "OG",
    sebekeKodu: "2033120",
    kesintiKokNedeni: "Bakım Çalışması",
    sinif_kaynağa: "Planlı",
    sinif_süreye: "Kısa",
    sinif_sebebe: "Onarım",
    sinif_bildirime: "Dahili",
    baslama: "2025-10-29 08:00",
    sonaErme: "2025-10-29 12:00",
    kesintiSuresiSaat: 4,
    mesken_og: 4,
    mesken_ag: 12,
    tarimsal_og: 2,
    tarimsal_ag: 6,
    ticarethane_og: 3,
    ticarethane_ag: 7,
    sanayi_og: 1,
    sanayi_ag: 3,
    enerji_mesken_og: 200,
    enerji_mesken_ag: 400,
    enerji_tarimsal_og: 150,
    enerji_tarimsal_ag: 250,
    enerji_ticarethane_og: 120,
    enerji_ticarethane_ag: 220,
    enerji_sanayi_og: 300,
    enerji_sanayi_ag: 600,
    total_not_delivered_kwh: 2240,
  },
  {
    kesintiKodu: "97083",
    kademe: "TM",
    il: "ŞANLIURFA",
    ilce: "HİLVAN",
    sebekeTipi: "AG",
    sebekeKodu: "2033121",
    kesintiKokNedeni: "Trafo Arızası",
    sinif_kaynağa: "Arıza",
    sinif_süreye: "Uzun",
    sinif_sebebe: "Kablo Hasarı",
    sinif_bildirime: "Acil",
    baslama: "2025-10-28 22:00",
    sonaErme: "2025-10-29 03:30",
    kesintiSuresiSaat: 5.5,
    mesken_og: 6,
    mesken_ag: 15,
    tarimsal_og: 1,
    tarimsal_ag: 5,
    ticarethane_og: 2,
    ticarethane_ag: 4,
    sanayi_og: 1,
    sanayi_ag: 1,
    enerji_mesken_og: 320,
    enerji_mesken_ag: 520,
    enerji_tarimsal_og: 100,
    enerji_tarimsal_ag: 180,
    enerji_ticarethane_og: 200,
    enerji_ticarethane_ag: 260,
    enerji_sanayi_og: 350,
    enerji_sanayi_ag: 550,
    total_not_delivered_kwh: 2480,
  },
  {
    kesintiKodu: "97084",
    kademe: "DM",
    il: "BATMAN",
    ilce: "BEŞİRİ",
    sebekeTipi: "OG",
    sebekeKodu: "2033122",
    kesintiKokNedeni: "Hat Yenileme",
    sinif_kaynağa: "Planlı",
    sinif_süreye: "Orta",
    sinif_sebebe: "Yatırım",
    sinif_bildirime: "Planlı",
    baslama: "2025-10-27 09:00",
    sonaErme: "2025-10-27 14:30",
    kesintiSuresiSaat: 5.5,
    mesken_og: 8,
    mesken_ag: 25,
    tarimsal_og: 3,
    tarimsal_ag: 8,
    ticarethane_og: 4,
    ticarethane_ag: 9,
    sanayi_og: 2,
    sanayi_ag: 4,
    enerji_mesken_og: 300,
    enerji_mesken_ag: 600,
    enerji_tarimsal_og: 250,
    enerji_tarimsal_ag: 300,
    enerji_ticarethane_og: 280,
    enerji_ticarethane_ag: 340,
    enerji_sanayi_og: 450,
    enerji_sanayi_ag: 700,
    total_not_delivered_kwh: 3220,
  },
  {
    kesintiKodu: "97085",
    kademe: "TM",
    il: "DİYARBAKIR",
    ilce: "ÇERMİK",
    sebekeTipi: "OG",
    sebekeKodu: "2033123",
    kesintiKokNedeni: "Direk Hasarı",
    sinif_kaynağa: "Arıza",
    sinif_süreye: "Kısa",
    sinif_sebebe: "Rüzgar",
    sinif_bildirime: "Acil",
    baslama: "2025-10-25 16:30",
    sonaErme: "2025-10-25 19:00",
    kesintiSuresiSaat: 2.5,
    mesken_og: 3,
    mesken_ag: 9,
    tarimsal_og: 0,
    tarimsal_ag: 3,
    ticarethane_og: 2,
    ticarethane_ag: 4,
    sanayi_og: 1,
    sanayi_ag: 1,
    enerji_mesken_og: 120,
    enerji_mesken_ag: 300,
    enerji_tarimsal_og: 0,
    enerji_tarimsal_ag: 120,
    enerji_ticarethane_og: 150,
    enerji_ticarethane_ag: 200,
    enerji_sanayi_og: 180,
    enerji_sanayi_ag: 250,
    total_not_delivered_kwh: 1320,
  },
  {
    kesintiKodu: "97086",
    kademe: "DM",
    il: "GAZİANTEP",
    ilce: "NİZİP",
    sebekeTipi: "AG",
    sebekeKodu: "2033124",
    kesintiKokNedeni: "Kablo Patlaması",
    sinif_kaynağa: "Arıza",
    sinif_süreye: "Uzun",
    sinif_sebebe: "Aşırı Yük",
    sinif_bildirime: "Acil",
    baslama: "2025-10-24 02:00",
    sonaErme: "2025-10-24 10:00",
    kesintiSuresiSaat: 8,
    mesken_og: 5,
    mesken_ag: 30,
    tarimsal_og: 1,
    tarimsal_ag: 4,
    ticarethane_og: 4,
    ticarethane_ag: 8,
    sanayi_og: 2,
    sanayi_ag: 3,
    enerji_mesken_og: 400,
    enerji_mesken_ag: 1000,
    enerji_tarimsal_og: 200,
    enerji_tarimsal_ag: 300,
    enerji_ticarethane_og: 250,
    enerji_ticarethane_ag: 400,
    enerji_sanayi_og: 500,
    enerji_sanayi_ag: 700,
    total_not_delivered_kwh: 3750,
  },
  {
    kesintiKodu: "97087",
    kademe: "TM",
    il: "MARDİN",
    ilce: "KIZILTEPE",
    sebekeTipi: "OG",
    sebekeKodu: "2033125",
    kesintiKokNedeni: "Bakım Onarım",
    sinif_kaynağa: "Planlı",
    sinif_süreye: "Orta",
    sinif_sebebe: "Periyodik",
    sinif_bildirime: "Planlı",
    baslama: "2025-10-23 08:00",
    sonaErme: "2025-10-23 13:30",
    kesintiSuresiSaat: 5.5,
    mesken_og: 4,
    mesken_ag: 10,
    tarimsal_og: 2,
    tarimsal_ag: 5,
    ticarethane_og: 3,
    ticarethane_ag: 6,
    sanayi_og: 1,
    sanayi_ag: 2,
    enerji_mesken_og: 200,
    enerji_mesken_ag: 300,
    enerji_tarimsal_og: 150,
    enerji_tarimsal_ag: 200,
    enerji_ticarethane_og: 220,
    enerji_ticarethane_ag: 260,
    enerji_sanayi_og: 250,
    enerji_sanayi_ag: 300,
    total_not_delivered_kwh: 1880,
  },
  {
    kesintiKodu: "97088",
    kademe: "DM",
    il: "BATMAN",
    ilce: "MERKEZ",
    sebekeTipi: "AG",
    sebekeKodu: "2033126",
    kesintiKokNedeni: "Planlı Bakım",
    sinif_kaynağa: "Planlı",
    sinif_süreye: "Kısa",
    sinif_sebebe: "Direk Değişimi",
    sinif_bildirime: "Planlı",
    baslama: "2025-10-22 07:00",
    sonaErme: "2025-10-22 10:00",
    kesintiSuresiSaat: 3,
    mesken_og: 2,
    mesken_ag: 7,
    tarimsal_og: 1,
    tarimsal_ag: 2,
    ticarethane_og: 2,
    ticarethane_ag: 3,
    sanayi_og: 1,
    sanayi_ag: 1,
    enerji_mesken_og: 100,
    enerji_mesken_ag: 200,
    enerji_tarimsal_og: 100,
    enerji_tarimsal_ag: 100,
    enerji_ticarethane_og: 150,
    enerji_ticarethane_ag: 200,
    enerji_sanayi_og: 250,
    enerji_sanayi_ag: 350,
    total_not_delivered_kwh: 1450,
  },
  {
    kesintiKodu: "97089",
    kademe: "TM",
    il: "GAZİANTEP",
    ilce: "OĞUZELİ",
    sebekeTipi: "OG",
    sebekeKodu: "2033127",
    kesintiKokNedeni: "Hat Değişimi",
    sinif_kaynağa: "Planlı",
    sinif_süreye: "Orta",
    sinif_sebebe: "Yatırım",
    sinif_bildirime: "Planlı",
    baslama: "2025-10-21 09:00",
    sonaErme: "2025-10-21 15:00",
    kesintiSuresiSaat: 6,
    mesken_og: 5,
    mesken_ag: 20,
    tarimsal_og: 2,
    tarimsal_ag: 6,
    ticarethane_og: 3,
    ticarethane_ag: 5,
    sanayi_og: 1,
    sanayi_ag: 3,
    enerji_mesken_og: 250,
    enerji_mesken_ag: 450,
    enerji_tarimsal_og: 200,
    enerji_tarimsal_ag: 250,
    enerji_ticarethane_og: 220,
    enerji_ticarethane_ag: 300,
    enerji_sanayi_og: 280,
    enerji_sanayi_ag: 420,
    total_not_delivered_kwh: 2370,
  },
  {
    kesintiKodu: "97090",
    kademe: "DM",
    il: "ŞIRNAK",
    ilce: "CİZRE",
    sebekeTipi: "AG",
    sebekeKodu: "2033128",
    kesintiKokNedeni: "Kısa Devre",
    sinif_kaynağa: "Arıza",
    sinif_süreye: "Kısa",
    sinif_sebebe: "Yağış",
    sinif_bildirime: "Acil",
    baslama: "2025-10-20 19:00",
    sonaErme: "2025-10-20 22:00",
    kesintiSuresiSaat: 3,
    mesken_og: 3,
    mesken_ag: 8,
    tarimsal_og: 0,
    tarimsal_ag: 2,
    ticarethane_og: 2,
    ticarethane_ag: 4,
    sanayi_og: 1,
    sanayi_ag: 2,
    enerji_mesken_og: 150,
    enerji_mesken_ag: 250,
    enerji_tarimsal_og: 0,
    enerji_tarimsal_ag: 80,
    enerji_ticarethane_og: 200,
    enerji_ticarethane_ag: 220,
    enerji_sanayi_og: 240,
    enerji_sanayi_ag: 350,
    total_not_delivered_kwh: 1490,
  },
  {
    kesintiKodu: "97091",
    kademe: "TM",
    il: "SİİRT",
    ilce: "MERKEZ",
    sebekeTipi: "OG",
    sebekeKodu: "2033129",
    kesintiKokNedeni: "Ekipman Arızası",
    sinif_kaynağa: "Arıza",
    sinif_süreye: "Orta",
    sinif_sebebe: "Transformatör",
    sinif_bildirime: "Acil",
    baslama: "2025-10-19 06:00",
    sonaErme: "2025-10-19 11:00",
    kesintiSuresiSaat: 5,
    mesken_og: 6,
    mesken_ag: 15,
    tarimsal_og: 1,
    tarimsal_ag: 3,
    ticarethane_og: 2,
    ticarethane_ag: 6,
    sanayi_og: 1,
    sanayi_ag: 2,
    enerji_mesken_og: 300,
    enerji_mesken_ag: 450,
    enerji_tarimsal_og: 180,
    enerji_tarimsal_ag: 220,
    enerji_ticarethane_og: 200,
    enerji_ticarethane_ag: 280,
    enerji_sanayi_og: 300,
    enerji_sanayi_ag: 400,
    total_not_delivered_kwh: 2330,
  },
  {
    kesintiKodu: "97092",
    kademe: "DM",
    il: "ŞANLIURFA",
    ilce: "BİRECİK",
    sebekeTipi: "AG",
    sebekeKodu: "2033130",
    kesintiKokNedeni: "Planlı Hat Genişletme",
    sinif_kaynağa: "Planlı",
    sinif_süreye: "Orta",
    sinif_sebebe: "Yatırım",
    sinif_bildirime: "Planlı",
    baslama: "2025-10-18 08:30",
    sonaErme: "2025-10-18 13:00",
    kesintiSuresiSaat: 4.5,
    mesken_og: 5,
    mesken_ag: 18,
    tarimsal_og: 1,
    tarimsal_ag: 5,
    ticarethane_og: 3,
    ticarethane_ag: 4,
    sanayi_og: 1,
    sanayi_ag: 1,
    enerji_mesken_og: 260,
    enerji_mesken_ag: 420,
    enerji_tarimsal_og: 120,
    enerji_tarimsal_ag: 200,
    enerji_ticarethane_og: 180,
    enerji_ticarethane_ag: 250,
    enerji_sanayi_og: 200,
    enerji_sanayi_ag: 300,
    total_not_delivered_kwh: 2150,
  },
  {
    kesintiKodu: "97093",
    kademe: "TM",
    il: "BATMAN",
    ilce: "KOZLUK",
    sebekeTipi: "OG",
    sebekeKodu: "2033131",
    kesintiKokNedeni: "Fırtına Hasarı",
    sinif_kaynağa: "Arıza",
    sinif_süreye: "Kısa",
    sinif_sebebe: "Doğal Olay",
    sinif_bildirime: "Acil",
    baslama: "2025-10-17 17:00",
    sonaErme: "2025-10-17 20:30",
    kesintiSuresiSaat: 3.5,
    mesken_og: 2,
    mesken_ag: 6,
    tarimsal_og: 0,
    tarimsal_ag: 1,
    ticarethane_og: 1,
    ticarethane_ag: 2,
    sanayi_og: 1,
    sanayi_ag: 1,
    enerji_mesken_og: 120,
    enerji_mesken_ag: 220,
    enerji_tarimsal_og: 0,
    enerji_tarimsal_ag: 50,
    enerji_ticarethane_og: 100,
    enerji_ticarethane_ag: 150,
    enerji_sanayi_og: 200,
    enerji_sanayi_ag: 250,
    total_not_delivered_kwh: 1090,
  },
];
