import { SmsListApiResponse } from "@/types/components/pages/settings/sms";

export const mockSmsApiResponse: SmsListApiResponse = {
  responseStatusCode: 200,
  responseMessage: "Mock SMS templates for local development",
  responseList: [
    {
      messageChannelTypeId: 1,
      messageTypeId: 1,
      content:
        "Sayın abonemiz, {İl} {İlçe} {Mahalle} için planlı kesintiniz {Planlı Başlangıç Tarihi} - {Planlı Bitiş Tarihi} arasında olacaktır. Nedeni: {Planlı Kesinti Nedeni}.",
      languageCode: "TR",
      isActive: true,
      startDateTime: "2026-05-18T14:00:00Z",
      endDateTime: "2026-05-18T18:00:00Z",
      concurrencyStamp: "",
      isDeleted: false,
      deleterId: null,
      deletionTime: null,
      lastModificationTime: "2026-05-18T12:00:00Z",
      lastModifierId: null,
      creationTime: "2026-05-18T10:00:00Z",
      creatorId: null,
      id: 1,
    },
    {
      messageChannelTypeId: 1,
      messageTypeId: 1,
      content:
        "Enerji veriliş saati tahmini: {Tahmini Enerji Veriliş Saati}. Tesisat No: {Tesisat Numarası}, Abone No: {Abone Numarası}.",
      languageCode: "TR",
      isActive: false,
      startDateTime: "2026-05-18T14:00:00Z",
      endDateTime: "2026-05-18T18:00:00Z",
      concurrencyStamp: "",
      isDeleted: false,
      deleterId: null,
      deletionTime: null,
      lastModificationTime: "2026-05-18T12:00:00Z",
      lastModifierId: null,
      creationTime: "2026-05-18T10:00:00Z",
      creatorId: null,
      id: 2,
    },
    {
      messageChannelTypeId: 1,
      messageTypeId: 1,
      content:
        "Duyuru: {İl} {İlçe} {Mahalle} bölgesinde plansız kesinti başladı. Başlangıç: {Plansız Başlangıç Tarihi}, Bitiş: {Plansız Bitiş Tarihi}, Nedeni: {Plansız Kesinti Nedeni}.",
      languageCode: "TR",
      isActive: false,
      startDateTime: "2026-05-18T14:00:00Z",
      endDateTime: "2026-05-18T18:00:00Z",
      concurrencyStamp: "",
      isDeleted: false,
      deleterId: null,
      deletionTime: null,
      lastModificationTime: "2026-05-18T12:00:00Z",
      lastModifierId: null,
      creationTime: "2026-05-18T10:00:00Z",
      creatorId: null,
      id: 3,
    },
  ],
};
